apiVersion: v1
kind: ConfigMap
metadata:
  name: lux-gaming-config
  namespace: lux-gaming
data:
  NODE_ENV: "development"
  HOST: "0.0.0.0"
  DB_HOST: "db-cluster.cluster-cqpwegg6ef7y.us-east-1.rds.amazonaws.com"
  JWT_EXPIRES_IN: "1d"
  LOG_LEVEL: "info"